const coursesData = [
  {
    _id: "1",
    courseTitle: "دوره جامع آموزش ری اکت",
    teacherName: "علی علوی",
    category: "برنامه نویسی وب",
    level: "پیشرفته",
    likeCount: 98,
    videoCount: 15,
    price: 500000,
    courseImage: require("../../assets/images/course-react.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-1.jpg"),
  },
  {
    _id: "2",
    courseTitle: "دوره جامع آموزش گراف کیوال",
    teacherName: "فاطمه صوری",
    category: "بانک اطلاعاتی",
    level: "متوسط",
    likeCount: 45,
    videoCount: 7,
    price: 350000,
    courseImage: require("../../assets/images/course-graphql.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-2.jpg"),
  },
  {
    _id: "3",
    courseTitle: "دوره جامع آموزش گتس بای",
    teacherName: "فاطمه صوری",
    category: "برنامه نویسی وب",
    level: "پیشرفته",
    likeCount: 81,
    videoCount: 4,
    price: 450000,
    courseImage: require("../../assets/images/course-gatsby.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-3.jpg"),
  },
  {
    _id: "4",
    courseTitle: "دوره جامع آموزش انگولار",
    teacherName: "فاطمه صوری",
    category: "برنامه نویسی وب",
    level: "متوسط",
    likeCount: 65,
    videoCount: 15,
    price: 450000,
    courseImage: require("../../assets/images/course-angular.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-1.jpg"),
  },
  {
    _id: "5",
    courseTitle: "دوره جامع آموزش جاوااسکریپت",
    teacherName: "فاطمه صوری",
    category: "برنامه نویسی وب",
    level: "مقدماتی",
    likeCount: 90,
    videoCount: 25,
    price: 450000,
    courseImage: require("../../assets/images/course-javascript.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-2.jpg"),
  },
  {
    _id: "6",
    courseTitle: "دوره جامع آموزش پایتون",
    teacherName: "فاطمه صوری",
    category: "دیتا ساینس",
    level: "پیشرفته",
    likeCount: 78,
    videoCount: 10,
    price: 450000,
    courseImage: require("../../assets/images/course-python.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-2.jpg"),
  },
  {
    _id: "7",
    courseTitle: "دوره جامع آموزش ووردپرس",
    teacherName: "علی علوی",
    category: "برنامه نویسی وب",
    level: "متوسط",
    likeCount: 35,
    videoCount: 20,
    price: 300000,
    courseImage: require("../../assets/images/course-wordpress.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-1.jpg"),
  },
  {
    _id: "8",
    courseTitle: "دوره جامع آموزش CSS",
    teacherName: "فاطمه صوری",
    category: "برنامه نویسی وب",
    level: "مقدماتی",
    likeCount: 81,
    videoCount: 55,
    price: 250000,
    courseImage: require("../../assets/images/course-css.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-2.jpg"),
  },
  {
    _id: "9",
    courseTitle: "دوره جامع آموزش SQL",
    teacherName: "فاطمه صوری",
    category: "بانک اطلاعاتی",
    level: "متوسط",
    likeCount: 50,
    videoCount: 25,
    price: 8500000,
    courseImage: require("../../assets/images/course-sql.png"),
    teacherImage: require("../../assets/images/teacher-thumb-2.jpg"),
  }
];

export default coursesData;
