const coursesData = [
  {
    _id: "1",
    courseTitle: "دوره جامع آموزش ری اکت",
    teacherName: "علی علوی",
    likeCount: 98,
    videoCount: 15,
    price: 500000,
    courseImage: require("../../assets/images/course-react.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-1.jpg"),
  },
  {
    _id: "2",
    courseTitle: "دوره جامع آموزش گراف کیوال",
    teacherName: "فاطمه صوری",
    likeCount: 45,
    videoCount: 7,
    price: 350000,
    courseImage: require("../../assets/images/course-graphql.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-2.jpg"),
  },
  {
    _id: "3",
    courseTitle: "دوره جامع آموزش گتس بای",
    teacherName: "فاطمه صوری",
    likeCount: 81,
    videoCount: 4,
    price: 450000,
    courseImage: require("../../assets/images/course-gatsby.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-3.jpg"),
  },
  {
    _id: "4",
    courseTitle: "دوره جامع آموزش انگولار",
    teacherName: "فاطمه صوری",
    likeCount: 65,
    videoCount: 15,
    price: 450000,
    courseImage: require("../../assets/images/course-angular.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-1.jpg"),
  },
  {
    _id: "5",
    courseTitle: "دوره جامع آموزش جاوااسکریپت",
    teacherName: "فاطمه صوری",
    likeCount: 90,
    videoCount: 25,
    price: 450000,
    courseImage: require("../../assets/images/course-javascript.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-2.jpg"),
  },
  {
    _id: "6",
    courseTitle: "دوره جامع آموزش پایتون",
    teacherName: "فاطمه صوری",
    likeCount: 78,
    videoCount: 10,
    price: 450000,
    courseImage: require("../../assets/images/course-python.jpg"),
    teacherImage: require("../../assets/images/teacher-thumb-2.jpg"),
  }
];

export default coursesData;
